MajorProject/config/routes.rb
Rails.application.routes.draw do
  get 'student/login'

  post 'student/index'

  get 'aboutus/introduction'

  get 'aboutus/credit'

  get 'aboutus/evaluation'

  get 'home/index', to: 'home#index'

  get 'home/aboutUs', to: 'home#aboutUs'
  
  get 'home/bestProject', to: 'home#bestProject'
  
  get 'home/downloadbook'
  
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MajorProject/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MajorProject/app/models/student.rb
class Student < ApplicationRecord
end

MajorProject/app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
  def introduction
  end

  def credit
  end

  def evaluation
  end
end

MajorProject/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

MajorProject/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def aboutUs
  end
  
  def bestProject
  end
  
  def downloadbook
  send_file Rails.root.join('public','ProjectHandbook.pdf'), :type=>"application/pdf", :x_sendfile=>true
  end
end

MajorProject/app/controllers/student_controller.rb
class StudentController < ApplicationController
  def login
  @student=Student.new
  end

  def index
    @student=Student.new(user_params)
	@newstudent=Student.find_by_firstname(@student.firstname)
  end
  def user_params
    params.require(:student).permit(:firstname,:password)
  end
end

MajorProject/app/helpers/aboutus_helper.rb
module AboutusHelper
end

MajorProject/app/helpers/application_helper.rb
module ApplicationHelper
end

MajorProject/app/helpers/home_helper.rb
module HomeHelper
end

MajorProject/app/helpers/student_helper.rb
module StudentHelper
end

MajorProject/app/views/aboutus/credit.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Major Project Management</title>

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>


<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- <a class="navbar-brand topnav" href="#">Have a look at our best projects</a> -->
				<%= link_to "Have a look at our best projects",{controller: "home",action: "bestProject"}, class:"navbar-brand topnav" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <!-- <a href="#about">About</a> -->
						<%= link_to "Home", controller: "home", action: "index" %>
                    </li>
					<li>
                        <!-- <a href="#about">About</a> -->
						<%= link_to "About", controller: "home", action: "aboutUs" %>
                    </li>
                   
                    <li>
                        <a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </
        <!-- /.container -->
    </nav>
<!-- Working till this -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <%= link_to "Introduction", {controller: "aboutus", action: "introduction"} %>
                    </li>
                    <li>
                        <%= link_to "Credit Structure", {controller: "aboutus", action: "credit"} %>
                    </li>
                    <li class="active">
                        <%= link_to "Evaluation", {controller: "aboutus", action: "evaluation"} %>
                    </li>
                    <li>
                        <%= link_to "Download Handbook", {controller: "home", action: "index"} %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

	

<h1>Aboutus#credit</h1>
<p>Find me in app/views/aboutus/credit.html.erb</p>

MajorProject/app/views/aboutus/evaluation.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Major Project Management</title>

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>


<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- <a class="navbar-brand topnav" href="#">Have a look at our best projects</a> -->
				<%= link_to "Have a look at our best projects",{controller: "home",action: "bestProject"}, class:"navbar-brand topnav" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <!-- <a href="#about">About</a> -->
						<%= link_to "Home", controller: "home", action: "index" %>
                    </li>
					<li>
                        <!-- <a href="#about">About</a> -->
						<%= link_to "About", controller: "home", action: "aboutUs" %>
                    </li>
                   
                    <li>
                        <a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </
        <!-- /.container -->
    </nav>
<!-- Working till this -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <%= link_to "Introduction", {controller: "aboutus", action: "introduction"} %>
                    </li>
                    <li>
                        <%= link_to "Credit Structure", {controller: "aboutus", action: "credit"} %>
                    </li>
                    <li class="active">
                        <%= link_to "Evaluation", {controller: "aboutus", action: "evaluation"} %>
                    </li>
                    <li>
                        <%= link_to "Download Handbook", {controller: "home", action: "index"} %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

	
  <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Evaluation Parameters 
                        </h1>
                    </div>
                </div>
                <!-- /.row -->

                <div class="row">
                    <div class="col-lg-6">
                        <h2>Criteria</h2>
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Semester</th>
                                        <th>Evaluation Time</th>
                                        <th>Research Based Project</th>
                                        <th>Implementation Based Project</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Fifth</td>
                                        <td>Mid September</td>
                                        <td>Literature survey/ Project Understanding, preliminary topic selection, motivation, and synopsis.
(Project progress: 10%-15%)
</td>
                                        <td>Outline of the Project (Objective, uses), preliminary topic selection, motivation, and synopsis.
(Project progress: 15%-20%)
</td>
                                    </tr>
                                    <tr>
                                        <td>Fifth</td>
                                        <td>Mid November</td>
                                        <td>Topic freezing, collection of related material (data set, tool understanding), and report.
(Project progress: 40%-50%)
</td>
                                        <td>Topic freezing, requirement gathering, required hardware/software collection & understanding, database design, and report.
(Project progress: 40%-50%)
</td>
                                    </tr>
                                    <tr>
                                        <td>Sixth</td>
                                        <td>Mid Feb</td>
                                        <td>Implementation/validation, challenges and issues
(Project progress: 60%-80%)
</td>
                                        <td>Interface design, Implementation (coding)
(Project progress: 60%-80%)
</td>
                                    </tr>
                                    <tr>
                                        <td>Sixth</td>
                                        <td>Mid April</td>
                                        <td>Final Implementation/outcome
(Project progress: 75%-100%)
</td>
                                        <td>Final working project/deployment
(Project progress: 75%-100%)
</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
      
	

MajorProject/app/views/aboutus/introduction.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Major Project Management</title>

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>


<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- <a class="navbar-brand topnav" href="#">Have a look at our best projects</a> -->
				<%= link_to "Have a look at our best projects",{controller: "home",action: "bestProject"}, class:"navbar-brand topnav" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <!-- <a href="#about">About</a> -->
						<%= link_to "Home", controller: "home", action: "index" %>
                    </li>
					<li>
                        <!-- <a href="#about">About</a> -->
						<%= link_to "About", controller: "home", action: "aboutUs" %>
                    </li>
                   
                    <li>
                        <a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </
        <!-- /.container -->
    </nav>
<!-- Working till this -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <%= link_to "Introduction", {controller: "aboutus", action: "introduction"} %>
                    </li>
                    <li>
                        <%= link_to "Credit Structure", {controller: "aboutus", action: "credit"} %>
                    </li>
                    <li class="active">
                        <%= link_to "Evaluation", {controller: "aboutus", action: "evaluation"} %>
                    </li>
                    <li>
                        <%= link_to "Download Handbook", {controller: "home", action: "index"} %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">
	
               <div class="jumbotron">
                    <h2>Importance of Good Project</h2>
                    <p>Engineering is first and foremost the application of knowledge. However, the application must be carried out with judgment, to ensure that the resultant system is effective and efficient, and that it is of benefit (which raises the issue of the ethical responsibilities of engineers – a topic for another day). The final year project is one of the primary mechanisms used by the University to provide you with an opportunity to gain experience in the practical, effective, efficient, and beneficial application of what you have been studying for the past several years. Naturally, you will continue to gain engineering experience after you graduate but the final year project will be your first exposure to the full rigor of engineering practice. It is essential that you learn from this exposure and practice all of the engineering methodologies involved. It is particularly important that you learn not just to apply what you know, but to apply it with judgment, with the ability to assess what you are doing and to be critical of it.</p>
                    
                    </p>
                </div>
			</div>
		</div>
<h1>Aboutus#introduction</h1>
<p>Find me in app/views/aboutus/introduction.html.erb</p>

MajorProject/app/views/home/aboutUs.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Major Project Management</title>

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>


<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- <a class="navbar-brand topnav" href="#">Have a look at our best projects</a> -->
				<%= link_to "Have a look at our best projects",{controller: "home",action: "bestProject"}, class:"navbar-brand topnav" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <!-- <a href="#about">About</a> -->
						<%= link_to "Home", controller: "home", action: "index" %>
                    </li>
					<li>
                        <!-- <a href="#about">About</a> -->
						<%= link_to "About", controller: "home", action: "aboutUs" %>
                    </li>
                   
                    <li>
                        <a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </
        <!-- /.container -->
    </nav>
<!-- Working till this -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <%= link_to "Introduction", {controller: "aboutus", action: "introduction"} %>
                    </li>
                    <li>
                        <%= link_to "Credit Structure", {controller: "aboutus", action: "credit"} %>
                    </li>
                    <li class="active">
                        <%= link_to "Evaluation", {controller: "aboutus", action: "evaluation"} %>
                    </li>
                    <li>
                        <%= link_to "Download Handbook", home_downloadbook_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

	

MajorProject/app/views/home/bestProject.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Major Project Management</title>

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>


<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- <a class="navbar-brand topnav" href="#">Have a look at our best projects</a> -->
				<%= link_to "Have a look at our best projects",{controller: "home",action: "bestProject"}, class:"navbar-brand topnav" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <!-- <a href="#about">About</a> -->
						<%= link_to "Home", controller: "home", action: "index" %>
                    </li>
					<li>
                        <!-- <a href="#about">About</a> -->
						<%= link_to "About", controller: "home", action: "aboutUs" %>
                    </li>
                   
                    <li>
                        <a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

	
	<a  name="services"></a>
    <div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">AANKHEN<h2>
					<h3>Jayant Balyan and Khushboo Pahwa,<br> Batch 2014</h3>
                    <p class="lead">A novel concept of having eyes through indoor navigation was selected as best Best B.Tech project in 2014. The students won cash prize of Rs 30,000/- </p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <!-- <img class="img-responsive" src="ipad.png" alt=""> -->
					<%= image_tag("jayant.jpg" , class: "img-responsive") %>
					
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->
<div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Interactive Display System</h2>
					<h3> Dikshima Guglani, Sandeep Sachdev, Vineet Gupta, <br>Batch 2016 </h3>
                    <p class="lead">A projection surface was converted into a surface with interactive functionality. This was done using infrared pen. User can drag, copy, move the icons and can write as well.</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <!-- <img class="img-responsive" src="dog.png" alt=""> -->
					<%= image_tag("vineet.jpg", class: "img-responsive") %>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->
	
<br>
<br>
<h1> We can add more here  </h1>

MajorProject/app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Major Project Management</title>

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>


<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- <a class="navbar-brand topnav" href="#">Have a look at our best projects</a> -->
				<%= link_to "Have a look at our best projects",{controller: "home",action: "bestProject"}, class:"navbar-brand topnav" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <!-- <a href="#about">About</a> -->
						<%= link_to "Home", controller: "home", action: "index" %>
                    </li>
					<li>
                        <!-- <a href="#about">About</a> -->
						<%= link_to "About", controller: "home", action: "aboutUs" %>
                    </li>
                   
                    <li>
                        <a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<br>
<br>
<!-- working till here, now adding new things -->


    <!-- Header -->
    <a name="about"></a>
    <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Welcome to Major Project Portal</h1>
                        <h3>An Initiative of Department of Computer Science & Engineering</h3>
						<h3>The NorthCap University</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li>
                                <!-- <a href="#" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Student</span></a> -->
                                <%= link_to "Student",{controller: "student",action: "login"}, class:"btn btn-default btn-lg"  %>
									
								</li>
                            <li>
                                <%= link_to "Faculty",{controller: "student",action: "login"}, class:"btn btn-default btn-lg" %>
								<!-- <a href="#" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Faculty</span></a> -->
                            </li>
                            <li>
                                <!-- <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Co-ordinator</span></a> -->
								<%= link_to "Co-ordinator",{controller: "home",action: "bestProject"}, class:"btn btn-default btn-lg" %>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->

</body>
</html>

MajorProject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MajorProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>